FROM node:20-alpine

WORKDIR /app

# Instalar dependências necessárias
RUN apk add --no-cache python3 make g++ gcc libc-dev linux-headers postgresql-client

# Copiar scripts de inicialização primeiro
COPY docker-entrypoint.sh ./
COPY wait-for-it.sh ./
RUN chmod +x ./docker-entrypoint.sh && \
    chmod +x ./wait-for-it.sh

# Copiar arquivos de configuração
COPY package*.json ./
COPY tsconfig*.json ./
COPY nest-cli.json ./

# Instalar dependências
RUN npm install

# Copiar o resto dos arquivos
COPY . .

# Recompilar bcrypt
RUN npm rebuild bcrypt --build-from-source

# Definir o entrypoint
ENTRYPOINT ["./docker-entrypoint.sh"]

# Comando para desenvolvimento com hot reload
CMD ["npm", "run", "start:dev"]