FROM node:20-alpine

WORKDIR /app

# Instalar dependências necessárias
RUN apk add --no-cache python3 make g++ gcc libc-dev linux-headers postgresql-client

# Copiar apenas os arquivos de configuração primeiro
COPY package*.json ./
COPY tsconfig*.json ./
COPY nest-cli.json ./

# Instalar dependências
RUN npm install

# Copiar o resto dos arquivos
COPY . .

# Recompilar bcrypt
RUN npm rebuild bcrypt --build-from-source

# Configurar scripts de inicialização
COPY docker-entrypoint.sh /usr/local/bin/
COPY wait-for-it.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-entrypoint.sh && \
    chmod +x /usr/local/bin/wait-for-it.sh

ENTRYPOINT ["docker-entrypoint.sh"]

# Comando para desenvolvimento com hot reload
CMD ["npm", "run", "start:dev"]